project:
  type: website
  output-dir: docs
website:
  title: "chips n dips"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AnanthaKrishnan147
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



